async (page) => {
  await page.setViewportSize({width:1280,height:720});
  await page.goto('http://127.0.0.1:8000/calculus.html?scope=two#functions');
  await page.evaluate(()=>{const data=JSON.parse(localStorage.getItem('calculus-study-v1'));data.scope='one';localStorage.setItem('calculus-study-v1',JSON.stringify(data));});
  await page.reload();
  if(await page.locator('.lesson-link[href="#chapter-09"]').count())throw Error('legacy scope must not alter the math-two path');
  await page.setViewportSize({width:1280,height:720});
  await page.locator('#reset-lab').scrollIntoViewIfNeeded();
  await page.locator('#reset-lab').click();
  await page.locator('.skip').focus();await page.keyboard.press('Enter');
  if(!page.url().endsWith('#functions'))throw Error('skip link changed lesson');
  await page.route('https://cdn.jsdelivr.net/**',route=>route.abort());
  await page.goto('http://127.0.0.1:8000/calculus.html#%E0%A4%A');
  await page.waitForSelector('#lab-graph svg');
  if(!await page.locator('.math-status').isVisible())throw Error('missing math fallback');
  await page.setViewportSize({width:320,height:740});
  if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1))throw Error('320px overflow');
  if(!page.url().endsWith('#algebra-bridge'))throw Error('Malformed route must return to first preparatory lesson');
  await page.evaluate(()=>{location.hash='functions';});
  await page.waitForSelector('#param-x');
  await page.locator('#param-x').fill('2');
  if(!(await page.locator('#lab-readout').innerText()).includes('4'))throw Error('offline slider failed');
  await page.unroute('https://cdn.jsdelivr.net/**');
  await page.setViewportSize({width:1440,height:1000});
  await page.goto('http://127.0.0.1:8000/calculus.html?scope=two#chapter-07/sph');
  await page.waitForSelector('.chapter-content');
  if(!await page.locator('[data-section="sph"]').isVisible())throw Error('explicit reference link must remain readable');
  if(!await page.locator('[data-section="polar"]').isVisible())throw Error('math two polar section missing');
  await page.goto('http://127.0.0.1:8000/calculus.html#chapter-07');
  await page.waitForSelector('.chapter-content');
  if(await page.locator('[data-section="sph"]').isVisible())throw Error('reference section entered default sequence');
  await page.goto('http://127.0.0.1:8000/calculus.html#chapter-12');
  await page.waitForSelector('#btn1');
  await page.locator('#btn1').click();
  if(!(await page.locator('#cur1').innerText()).includes('22'))throw Error('matrix next-step control broken');
  await page.goto('file:///G:/vs/model/calculus.html#chapter-12');
  await page.waitForSelector('.chapter-content canvas');
  if(await page.locator('#retry-chapter').count())throw Error('local file chapter loading failed');
  await page.goto('http://127.0.0.1:8000/calculus.html#derivative');
  await page.setViewportSize({width:1440,height:1000});
  await page.screenshot({path:'output/playwright/desktop-derivative.png'});
  console.log('Scope reload, short viewport, keyboard skip, malformed hash, CDN failure and 320px layout passed.');
}
